import Head from 'next/head';
import { Box } from '@chakra-ui/layout';
import Header from './Header';

const Layout = ({ children }) => {
  return (
    <Box as="main" minHeight="80vh">
      <Head>
        <title>Echoes | Social Media Tools for Ease of Engagement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </Box>
  );
};

export default Layout;
